prog4_HF_zu68fr/Allatkert.Web/Models/Gondozo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Allatkert.Web.Models
{
    // Form modell
    public class Gondozo
    {
        [Required]  //ha valami kötelező
        [Display(Name ="Gondozó ID")]   //megjelenítendő neve
        public int Id { get; set; }

        [Required]
        [Display(Name = "Gondozó neve")]
        public string Nev { get; set; }

        [Required]
        [Display(Name = "Telefonszám")]
        public string TelSzam { get; set; }
        
        [Required]
        [Display(Name = "Munkaviszony kezdete")]
        public DateTime MunkaKezd { get; set; }
        
        [Display(Name = "Munkaviszony vége")]
        public DateTime MunkaVeg { get; set; }
    }
}

prog4_HF_zu68fr/Allatkert.Web/Models/GondozoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Allatkert.Web.Models
{
    public class GondozoViewModel
    {
        public Gondozo EditedGondozo { get; set; }
        public List<Gondozo> ListOfGondozo { get; set; }


    }
}

prog4_HF_zu68fr/Allatkert.Web/Controllers/GondozoController.cs
using Allatkert.Logic;
using Allatkert.Web.Models;
using AutoMapper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Allatkert.Repository;
using Allatkert.Data;

namespace Allatkert.Web.Controllers
{
    public class GondozoController : Controller
    {
        IGondozokLogic logic;
        IMapper mapper;
        GondozoViewModel vm;
        // asp.net core-ban: transient + automatic dependency injection => automata IoC

        public GondozoController()
        {
            //TODO:  connstring   progarm.appconfig => webes, web.config
            //TODO: copy db, kézzel => App_Data\
            //így most csak akkor "áll vissza", ha visszamásolom
            Model1 ctx = new Model1();
            GondozokRepository gondozoRepo = new GondozokRepository(ctx);
            logic = new GondozokLogic(gondozoRepo);
            mapper = MapperFactory.CreateMapper();
            //Better: Automatic IoC
            vm = new GondozoViewModel();
            vm.EditedGondozo = new Gondozo();
            var gondozok = logic.GetAllGondozok();
            //vm.ListOfGondozo = gondozok; ->converter
            vm.ListOfGondozo = mapper.Map<IList<Data.Gondozok>,List<Models.Gondozo>>(gondozok);

        }

        private Gondozo GetGondozoModel(int id)
        {
            Data.Gondozok oneGondozo = logic.GetOneGondozok(id.ToString());
            return mapper.Map<Data.Gondozok, Models.Gondozo>(oneGondozo);
        }

        // GET: Gondozo
        public ActionResult Index()
        {
            ViewData["editAction"] = "AddNew";  //csak ritkán használd, NAGYONNAGYON ritkán
            return View("GondozoIndex",vm);
        }

        // GET: Gondozo/Details/5
        public ActionResult Details(int id)
        {
            //var valami = GetGondozoModel(id);
            return View("GondozoDetails",GetGondozoModel(id));
        }

        //2x Del/Edit/Create helyett
        //1x Del, 1x Edit+GET, 1x Edit+POST

        public ActionResult Remove(int id)//remove, mert ugyanannak a névnek kell lennie mint a Gondozo.cshtml-ben
        {
            TempData["editResult"] = "Del failed";
            if (logic.DeleteGondozok(id.ToString()))
            {
                TempData["editResult"] = "Del OK";
            }
            return RedirectToAction(nameof(Index));   //átdob index metódusra
        }

        public ActionResult Edit(int id)
        {
            ViewData["editAction"] = "Edit";
            vm.EditedGondozo = GetGondozoModel(id);
            return View("GondozoIndex", vm);
        }

        [HttpPost]
        public ActionResult Edit(Gondozo gondozo, string editAction)
        {
            if (ModelState.IsValid && gondozo!=null)
            {
                TempData["editResult"] = "Edit OK";
                if (editAction=="AddNew")
                {
                    logic.InsertGondozok(gondozo.Id.ToString(), gondozo.Nev, gondozo.TelSzam, 
                        gondozo.MunkaKezd.ToString(), gondozo.MunkaVeg.ToString());
                }
                else
                {
                    bool success = logic.UpdateGondozok(gondozo.Id.ToString(),gondozo.Nev,gondozo.TelSzam,
                        gondozo.MunkaKezd.ToString(),gondozo.MunkaVeg.ToString());
                    if (!success)
                    {
                        TempData["editResult"] = "Edit FAIL";
                    }
                }
                return RedirectToAction(nameof(Index));
                
            }
            else   //felvett adat hibás
            {
                ViewData["editAction"] = "Edit";
                vm.EditedGondozo = gondozo;
                return View("GondozoIndex", vm);
            }
        }
    }
}

prog4_HF_zu68fr/Allatkert.Web/Views/Gondozo/GondozoDetails.cshtml
@model Allatkert.Web.Models.Gondozo
@{
    ViewBag.Title = "GondozoDetails";
}

<h2>GondozoDetails</h2>

<!-- <a href="~/Allatkert/Index">Back to the list</a>" -->
@Html.ActionLink("Back to the list", "Index");  <!--ugyanaz és sokszor hatékonyabb -->


<table border="1">
    <tr>
        <td>Gondozo ID: </td>
        <td>@Model.Id</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Nev)</td>
        <td>@Html.DisplayFor(m => m.Nev)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.TelSzam)</td>
        <td>@Html.DisplayFor(m => m.TelSzam)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.MunkaKezd)</td>
        <td>@Html.DisplayFor(m => m.MunkaKezd)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.MunkaVeg)</td>
        <td>@Html.DisplayFor(m => m.MunkaVeg)</td>
    </tr>
</table>

prog4_HF_zu68fr/Allatkert.Web/Views/Gondozo/GondozoEdit.cshtml
@model Allatkert.Web.Models.Gondozo

<h2>Edit one Gondozo</h2>

@using (Html.BeginForm("Edit", "Gondozo"))
{
    @Html.ValidationSummary()

    @Html.AntiForgeryToken()
    //cross-site request forgery ellen

    @Html.HiddenFor(m=>m.Id)
    @Html.Hidden("editAction",ViewData["editAction"].ToString())    // csak óvatosan, szét  

    <div class="editor-label">@Html.LabelFor(m => m.Nev)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Nev)</div>

    <div class="editor-label">@Html.LabelFor(m => m.TelSzam)</div>
    <div class="editor-field">@Html.EditorFor(m => m.TelSzam)</div>

    <div class="editor-label">@Html.LabelFor(m => m.MunkaKezd)</div>
    <div class="editor-field">@Html.EditorFor(m => m.MunkaKezd)</div>

    <div class="editor-label">@Html.LabelFor(m => m.MunkaVeg)</div>
    <div class="editor-field">@Html.EditorFor(m => m.MunkaVeg)</div>

    <input type="submit" value="SEND" />
}

prog4_HF_zu68fr/Allatkert.Web/Views/Gondozo/GondozoIndex.cshtml
@model Allatkert.Web.Models.GondozoViewModel
@{
    ViewBag.Title = "GondozoIndex";
}

<h2>Gondozo Index</h2>

<p style="color:red; font-weight:bold">@TempData["editResult"]</p>

@Html.Partial("GondozoEdit",Model.EditedGondozo)    <!--megkapja ugyanazt a modelt, tehát a viewModelt,ezért kell 2. paraméter-->

@Html.Partial("GondozoList",Model.ListOfGondozo)

prog4_HF_zu68fr/Allatkert.Web/Views/Gondozo/GondozoList.cshtml
@model IEnumerable<Allatkert.Web.Models.Gondozo>

<h2>List of cars</h2>
@if(Model.Count()==0)
{
    <p>Nincs adat :(</p>
}
else
{
    <table border="1">
        <tr>
            <th>@Html.DisplayNameFor(m => m.First().Nev)</th>
            <th>@Html.DisplayNameFor(m => m.First().TelSzam)</th>
            <th>Dataset</th>
            <th>Delete</th>
            <th>Edit</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(m => item.Nev)</td>
                <td>@Html.DisplayFor(m => item.TelSzam)</td>
                <td>@Html.ActionLink("SHOW","Details", new { id=item.Id })</td>
                <td>@Html.ActionLink("DEL", "Remove", new { id = item.Id })</td>
                <td>@Html.ActionLink("EDIT", "Edit", new { id = item.Id })</td>
            </tr>
         }
    </table>
}